export default function Head() {
  return (
    <>
      <title>Budget App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://www.flaticon.com/free-icons/budget" />
    </>
  )
}